### ISSUE TITLE
Links are without www but only works on www

### ISSUE THREAD

**Issue by jakobrosenberg** [peppercornstudio/pollen#16]
If I click **Tweet it** or the **satchel** link I get links without `www` which 404s.

PS. LOVE this project! It's everything I wanted a certain other CSS framework to be.

---

![image](https://user-images.githubusercontent.com/4153004/120914133-49c86600-c69c-11eb-909b-11ddb4f55d9d.png)

![image](https://user-images.githubusercontent.com/4153004/120914150-5b117280-c69c-11eb-91d7-4b7132b9e8e0.png)

**Comment by madeleineostoja** [comment]
Oop thanks for the heads up! Must be something wrong with my DNS, I'll get it sorted soon! And so glad you enjoy Pollen :)

**Comment by madeleineostoja** [comment]
So I looked into this and apex domains are pretty much impossible on Gitbook. Just removed all references to the apex domain for now, thanks for flagging!
