### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by bennypowers** [peppercornstudio/pollen#22]
Thanks for publishing this nice-looking library.

This issue is to suggest a new docs feature for the gitdocs page and for the README. Putting some screenshots on the docs pages and in the README would help new users get to know the library, get a sense for what it can do visually.

**Comment by madeleineostoja** [comment]
Good idea! Since it's not a UI library in the sense of having any prebuilt style, what sort of thing would you think would be helpful? Things like colour palettes and type scales maybe?

**Comment by bennypowers** [comment]
maybe a maquette of a layout with some swatches, typography, white spacings, etc?

**Comment by simonmcconnell** [comment]
Box shadow, for example.

**Comment by madeleineostoja** [comment]
Added mockups where it made sense / was possible with SVGs in gitbook

eg:
<img width="986" alt="Screen Shot 2021-11-09 at 11 57 06 PM" src="https://user-images.githubusercontent.com/6374876/140911937-952ce27c-6018-403b-92b9-63207977acc4.png">
