### ISSUE TITLE
Create Twitter account

### ISSUE THREAD

**Issue by fuzenco** [peppercornstudio/pollen#26]
I follow CSS projects on Twitter. I think creating your own Pollen Twitter account, for at the very least releases, would help expose this great project.

**Comment by madeleineostoja** [comment]
Hey thanks for the idea! I don’t know if I have enough to tweet about outside of releases, which _hopefully_ won’t happen to often now it’s fairly stable and defined. I’ll think about it though! Could always be a good way to showcase projects etc using it if we gain some more momentum

**Comment by fuzenco** [comment]
Agreed on the projects. And you’d be surprised at how much content you _already_ have. Even taking a snippet of your docs (example by example) could be content for each tweet.

I’ve found Twitter brings some legitimacy to projects. And it gives people a chance to discover new tools.

**Comment by madeleineostoja** [comment]
Gonna close this for now because I don't think I'll have time to maintain a twitter acc for Pollen unfortunately 😩 If I get some more time to start a dev focussed twitter presence I'll revisit.
