### ISSUE TITLE
[Feature] Adding a CSS reset

### ISSUE THREAD

**Issue by marekhoeven** [peppercornstudio/pollen#27]
Would there perhaps be a need for adding some basic CSS reset or normalization to Pollen? It could help with cross-browser inconsistencies.

**Comment by madeleineostoja** [comment]
Not sure that’s in the scope of Pollen, there are already so many really solid reset/normalisation libraries out there (cssremedy is my fave), I don’t know what adding one to pollen would bring to the table.

**Comment by marekhoeven** [comment]
Fair enough, it would work for me in the sense of just pulling in pollen.css and be done with the most basic CSS principles. But I can understand that CSS resets are often opinionated, and might repel some new users.

**Comment by madeleineostoja** [comment]
I'll close this for now, but if others think it could be a worthwhile thing to explore happy to reopen
