### ISSUE TITLE
Doc value errors?

### ISSUE THREAD

**Issue by fuzenco** [peppercornstudio/pollen#28]
In the case of Widths and Radius, the example snippet shows a numeric value but the default/standard properties don’t match. For instance, there isn’t an 11, but rather xs, md, and so on. Those are the only two places in docs where I saw that discrepancy.

![726A927E-DE15-4DA0-8275-A5BD90F96F33](https://user-images.githubusercontent.com/173683/133884944-d07314a4-5483-4625-85b3-6007995f0e14.jpeg)
![73914468-20F6-4E8C-A529-5E62FE0B1778](https://user-images.githubusercontent.com/173683/133884945-28db3104-1f68-497a-af57-86846d762d3b.jpeg)

**Comment by madeleineostoja** [comment]
Oops sorry! The examples haven’t been updated from Pollen v1, I’ll fix it up when I’m back at my computer. Thanks for flagging!
